version: '3.9'

services:
    identity:
        build:
            context: .
            dockerfile: IdentityService/Dockerfile
        container_name: identity_service
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

    identity-db:
        image: postgres
        container_name: identity_db
        environment:
            POSTGRES_DB: IdentityServiceDb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres-pw-secret
        ports:
            - 5432:5432
        volumes:
            - identity-service-data:/var/lib/postgres

volumes:
    identity-service-data: