version: '3.9'

services:
  identity-api:
    build:
      context: .
      dockerfile: src/IdentityService.API/Dockerfile
    container_name: identity_api
    ports:
      - "5000:80"
    depends_on:
      - identity-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - identity-net

  identity-db:
    image: postgres:16
    container_name: identity_db
    restart: always
    environment:
      POSTGRES_DB: IdentityDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    networks:
      - identity-net

volumes:
  identity-db-data:

networks:
  identity-net:
